name: cicdturbochat

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    defaults:
      run:
        working-directory: /var/www/html/gitActionTurbochat
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Setup Application
        run: |
          cd /var/www/html/gitActionTurbochat/turbochat/turbochat
          bundle install
          bin/rails db:create
          bin/rails db:migrate
          fuser -k 3000/tcp

      # The following line is not recommended in a CI/CD workflow
      # - run: fuser -k 3000/tcp

      # Instead, you can start the Rails server in the background
      - name: Start Rails Server
        run: |
          cd /var/www/html/gitActionTurbochat/turbochat/turbochat
          bin/rails server -p 3000
