name: turbochat

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /var/www/html/turbochat
    steps:
      run: |
        bundle install
        bin/rails db:create
        bin/rails db:migrate
        fuser -k 3000/tcp
        bin/rails s -d
