name: turbochat

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up database
        env:
          RAILS_ENV: development
        run: |
          bundle install
          bin/rails db:create
          bin/rails db:migrate
          fuser -k 3000/tcp
          bin/rails s -d
