name: cicdturbochat

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    defaults:
      run:
        #working directory of runner
        working-directory: /var/www/html/gitActionTurbochat/turbochat/turbochat
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Setup Application
        run: |
          bundle install
          bin/rails db:create
          bin/rails db:migrate

      # The following line is not recommended in a CI/CD workflow
      # - run: fuser -k 3000/tcp

      # Instead, you can start the Rails server in the background and prevent the pid to cleanup
      - name: Start Rails Server
        run: |
          RAILS_ENV=production rails secret
          RAILS_ENV=production bundle exec rails assets:precompile
          RUNNER_TRACKING_ID="" && (bundle exec rake server:restart)
